{% set version = "2.14.1" %}

package:
  name: fontconfig
  version: {{ version }}

source:
  url: https://www.freedesktop.org/software/fontconfig/release/fontconfig-{{ version }}.tar.gz
  sha256: ae480e9ca34382790312ff062c625ec70df94d6d9a9366e2b2b3d525f7f90387
  patches:
    # This patch won't be submitted upstream. It's use here is to ensure the prefix used
    # to refer to the `fonts.conf` file.
    - fcf.patch       # [linux]
    - 0001-Disable-test-bz106632.patch    # [win or osx]
    - osx_arm64.patch  # [osx and arm64]
build:
  number: 0
  skip: True                      # [win]
  binary_has_prefix_files:        # [unix]
    - lib/libfontconfig.so.1.*    # [linux]
    - lib/libfontconfig.*.dylib*  # [osx]
  run_exports:
    # remove symbols basically never (once, in 2006).
    #    https://abi-laboratory.pro/tracker/timeline/fontconfig/
    - {{ pin_subpackage('fontconfig') }}

requirements:
  build:
    - {{ compiler('c') }}
    - make
    - pkg-config
    - gperf
    - expat
    - gettext                     # [not win]
    - libtool
    - automake
    - autoconf
    - patch       # [not win]
    - m2-patch    # [win]

  host:
    - freetype
    - libxml2
    # Commenting out to avoid overdepending errors on macOS; `./configure`
    # fails to correctly pick up libiconv, even with explicitly invoked with
    # `--enable-iconv` and `--with-libiconv-prefix`.
    - libiconv                    # [not linux and not win]
    - libuuid                     # [linux]

test:
  commands:
    # Test CLI.
    - fc-cache --help
    - fc-cat --help
    - fc-list --help
    - fc-match --help
    - fc-pattern --help
    - fc-query --help
    - fc-scan --help
    - fc-validate --help

    # Test for libraries.
    - test -f "${PREFIX}/lib/libfontconfig.a"
    - test -f "${PREFIX}/lib/libfontconfig.dylib"  # [osx]
    - test -f "${PREFIX}/lib/libfontconfig.so"     # [linux]

about:
  home: http://www.freedesktop.org/wiki/Software/fontconfig/
  license: MIT
  license_file: COPYING
  summary: 'A library for configuring and customizing font access.'
  description: |
    Fontconfig is a library designed to provide system-wide font configuration,
    customization and application access.
  doc_url: https://www.freedesktop.org/software/fontconfig/fontconfig-user.html
  dev_url: https://cgit.freedesktop.org/fontconfig/

extra:
  recipe-maintainers:
    - ccordoba12
    - jakirkham
    - mingwandroid
    - ocefpaf
    - pkgw
