{% set name = "fontconfig" %}
{% set version = "2.18.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://gitlab.freedesktop.org/{{ name }}/{{ name }}/-/archive/{{ version }}/{{ name }}-{{ version }}.tar.gz
  sha256: a84d41b57cfb015783d7973b398c26d8763a64b803f97f31fa126fd2aa5eaaca
  patches:
    - patches/fcf.patch             # [unix]
    - patches/windows-compat.patch  # [win]

build:
  number: 0
  binary_has_prefix_files:        # [unix]
    - lib/libfontconfig.so.1.*    # [linux]
    - lib/libfontconfig.*.dylib*  # [osx]
  run_exports:
    # remove symbols basically never (once, in 2006).
    #    https://abi-laboratory.pro/tracker/timeline/fontconfig/
    - {{ pin_subpackage('fontconfig') }}

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - make   # [not win]
    - pkg-config
    - gperf  # [not win]
    - msys2-gperf  # [win]
    - expat
    - gettext   # [not win]
    - libtool   # [not win]
    - automake  # [not win]
    - autoconf  # [not win]
    - patch     # [not win]
    - python  # [win]
    - meson   # [win]
    - ninja   # [win]
  host:
    - freetype
    - libxml2 {{ libxml2 }}
    - coreutils  # [osx]
    # Required for MT-safe global config test
    - unzip      # [not win]
    - expat
    - libiconv   # [win]
    - libuuid    # [linux]
    - zlib {{ zlib }}

test:
  requires:
    - pkg-config

about:
  home: https://www.freedesktop.org/wiki/Software/fontconfig
  license: MIT
  license_file: COPYING
  license_family: MIT
  summary: A library for configuring and customizing font access
  description: |
    Fontconfig is a library designed to provide system-wide font configuration,
    customization and application access.
  doc_url: https://www.freedesktop.org/software/fontconfig/fontconfig-user.html
  dev_url: https://gitlab.freedesktop.org/fontconfig/fontconfig

extra:
  recipe-maintainers:
    - ccordoba12
    - jakirkham
    - katietz
    - mingwandroid
    - ocefpaf
    - pkgw
