{% set version = "2.12.1" %}

package:
  name: fontconfig
  version: {{ version }}

source:
  fn: fontconfig-{{ version }}.tar.bz2
  url: http://www.freedesktop.org/software/fontconfig/release/fontconfig-{{ version }}.tar.bz2
  sha256: b449a3e10c47e1d1c7a6ec6e2016cca73d3bd68fbbd4f0ae5cc6b573f7d6c7f3
  patches:
    # This patch won't be submitted upstream. It's use here is to ensure the prefix used
    # to refer to the `fonts.conf` file.
    - fcf.patch       # [linux]

build:
  number: 4
  skip: True                      # [win]
  binary_has_prefix_files:        # [linux]
    - lib/libfontconfig.so.1.9.2  # [linux]

requirements:
  host:
    - freetype 2.7|2.7.*
    - libiconv                    # [not linux and not win]
    - libpng >=1.6.28,<1.7
    - libxml2 2.9.*
    - icu 58.*  # [not win]
    - {{ compiler('c') }}

  build:
    - pkg-config
    - libtool

  run:
    - freetype 2.7|2.7.*
    - libiconv                    # [not linux and not win]
    - libpng >=1.6.28,<1.7
    - libxml2 2.9.*
    - icu 58.*  # [not win]

test:
  commands:
    # Test CLI.
    - fc-cache --help
    - fc-cat --help
    - fc-list --help
    - fc-match --help
    - fc-pattern --help
    - fc-query --help
    - fc-scan --help
    - fc-validate --help

    # Test for libraries.
    - test -f "${PREFIX}/lib/libfontconfig.a"
    - test -f "${PREFIX}/lib/libfontconfig.dylib"  # [osx]
    - test -f "${PREFIX}/lib/libfontconfig.so"     # [linux]
    - conda inspect linkages -p $PREFIX fontconfig  # [not win]
    - conda inspect objects -p $PREFIX fontconfig  # [osx]

about:
  home: http://www.freedesktop.org/wiki/Software/fontconfig/
  license: MIT
  license_file: COPYING
  summary: 'A library for configuring and customizing font access.'
  description: |
    Fontconfig is a library designed to provide system-wide font configuration,
    customization and application access.
  doc_url: https://www.freedesktop.org/software/fontconfig/fontconfig-user.html
  dev_url: https://cgit.freedesktop.org/fontconfig/

extra:
  recipe-maintainers:
    - ccordoba12
    - jakirkham
    - ocefpaf
    - pkgw
